POST http://localhost:8080/sign_up
Content-Type: application/json

{
  "email": "batrshintimur@yandex.ru",
  "password": "Timur007",
  "firstName": "Timur",
  "lastName" : "Batrshin"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "batrshintimur@yandex.ru",
  "password": "Timur007"
}


###

GET http://localhost:8080/logout
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Iiwicm9sZSI6IkFETUlOIiwic3RhdGUiOiJBQ1RJVkUiLCJlbWFpbCI6ImJhdHJzaGludGltdXJAeWFuZGV4LnJ1In0.CUmDCsoxDOK1SWT1b33wnClo4y3Ua0GeJ57uAp4EkBY

###
POST http://localhost:8080/users/2/block
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZSI6IlVTRVIiLCJzdGF0ZSI6IkFDVElWRSIsImVtYWlsIjoiYmF0cnNoaW50aW11ckB5YW5kZXgucnVyIn0.BdRGHcd0NjeIgG69s5rMCmhvefqxopQ65WefKjLMC2k


###
POST http://localhost:8080/pdf/generate
Content-Type: application/json

{
  "firstName": "Timur"
}


