<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://image.freepik.com/free-vector/vintage-burger-hand-drawn-logo-illustration_43582-60.jpg" alt="">
<h2><a href="${server_url}/confirm/${confirm_code}/sign_in">Пройдите по ссылке</a></h2>
</body>
</html>
