<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://fiba3x3.com/img/3x3-logo-cut.svg" alt="">
<h2><a href="${server_url}/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>
