POST http://localhost:8080/sign_up
Content-Type: application/json

{
  "email": "batrshintimur@yandex.ru",
  "password": "Timur007",
  "userName": "Timur"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "password": "Timur007",
  "email": "batrshintimur@yandex.ru",
  "deviceFingerprint": "idea"
}